### ISSUE TITLE
Error when starting local

### ISSUE THREAD

**Issue by drizt** [urish/beat-machine#47]
```
[taurus@lix beat-machine]$ node --version
v18.18.2
[taurus@lix beat-machine]$ npm --version
9.8.1
[taurus@lix beat-machine]$ npm run dev

> beat-machine@1.0.0 dev
> next dev -p 3009

Error: Next.js requires react >= 18.2.0 to be installed.
    at Object.<anonymous> (/home/taurus/develop/beat-machine/node_modules/next/dist/build/webpack-config.js:135:11)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at mod.require (/home/taurus/develop/beat-machine/node_modules/next/dist/server/require-hook.js:64:28)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Object.<anonymous> (/home/taurus/develop/beat-machine/node_modules/next/dist/server/dev/hot-reloader-webpack.js:34:64)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
```

**Comment by drizt** [comment]
Solved with `npm install react@latest`
